"""add_oauth_social_profile_fields

Revision ID: 527d3b33e0e0
Revises: 8a34b4704b8d
Create Date: 2026-02-24 15:03:44.230525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527d3b33e0e0'
down_revision: Union[str, None] = '8a34b4704b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('provider_username', sa.String(length=255), nullable=True))
    op.add_column('oauth_accounts', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('oauth_accounts', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('oauth_accounts', sa.Column('profile_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_accounts', 'profile_data')
    op.drop_column('oauth_accounts', 'avatar_url')
    op.drop_column('oauth_accounts', 'display_name')
    op.drop_column('oauth_accounts', 'provider_username')
    # ### end Alembic commands ###
