"""add_onboarding_step_to_seller_profiles

Revision ID: 559a2c220dbd
Revises: 4e479c8f40f2
Create Date: 2026-02-22 20:25:55.978514
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559a2c220dbd'
down_revision: Union[str, None] = '4e479c8f40f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('onboarding_step', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_profiles', 'onboarding_step')
    # ### end Alembic commands ###
